accounts/passwords/urls.py
# accounts.passwords.urls.py 
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns  = [
        url(r'^password/change/$', 
                auth_views.PasswordChangeView.as_view(), 
                name='password_change'),
        url(r'^password/change/done/$',
                auth_views.PasswordChangeDoneView.as_view(), 
                name='password_change_done'),
        url(r'^password/reset/$', 
                auth_views.PasswordResetView.as_view(), 
                name='password_reset'),
        url(r'^password/reset/done/$', 
                auth_views.PasswordResetDoneView.as_view(), 
                name='password_reset_done'),
        url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 
                auth_views.PasswordResetConfirmView.as_view(), 
                name='password_reset_confirm'),
        url(r'^password/reset/complete/$', 
                auth_views.PasswordResetCompleteView.as_view(), 
                name='password_reset_complete'),
]

accounts/urls.py
from django.conf.urls import url
from django.urls import path

from products.views import UserProductHistoryView
from .views import (
        AccountHomeView, 
        AccountEmailActivateView,
        UserDetailUpdateView
        )

from .views import StripeAuthorizeView, StripeAuthorizeCallbackView

urlpatterns = [
    path('authorize/', StripeAuthorizeView.as_view(), name='authorize'),
    path('oauth/callback/', StripeAuthorizeCallbackView.as_view(), name='authorize_callback'),
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', 
            AccountEmailActivateView.as_view(), 
            name='email-activate'),
    url(r'^email/resend-activation/$', 
            AccountEmailActivateView.as_view(), 
            name='resend-activation'),
    
]
app_name = 'accounts'
# account/email/confirm/asdfads/ -> activation view

carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]
app_name = 'carts'

orders/urls.py
from django.conf.urls import url

from .views import (
        OrderListView, 
        OrderDetailView,
        VerifyOwnership
        )

urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='list'),
    url(r'^endpoint/verify/ownership/$', VerifyOwnership.as_view(), name='verify-ownership'),
    url(r'^(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='detail'),
]
app_name = 'orders'

products/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
        ProductListView, 
        ProductDetailSlugView,
        ProductDownloadView,
        remove_single_item_from_cart,
        add_to_cart,
        add_product_view,
        ProductChargeView
        )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
	path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('charge/', ProductChargeView.as_view(), name='charge'),
    url(r'^add_product/$', add_product_view, name='add_product'),

    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),
]

app_name = 'products'

stores/urls.py
from django.conf.urls import url
from .views import store_list_view , StoreDetailSlugView ,add_store_view
  


urlpatterns = [
	url(r'^$', store_list_view, name='list'),
	url(r'^add_store/$', add_store_view, name='add_store'),

	url(r'^(?P<id>[\w-]+)/$', StoreDetailSlugView, name='detail'),
]
app_name = 'stores'

accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.views.generic.edit import FormMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.utils.http import is_safe_url
from django.utils.safestring import mark_safe
from django.conf import settings
import requests
import urllib
from ecommerce.mixins import NextUrlMixin, RequestFormAttachMixin
from .forms import (LoginForm,
                    RegisterForm, 
                    GuestForm, 
                    ReactivateEmailForm,
                    UserDetailChangeForm,
                    
             )
from .models import GuestEmail, EmailActivation ,Seller
from .signals import user_logged_in


class StripeAuthorizeView(View):

    def get(self, request):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse('/login/'))
        url = 'https://connect.stripe.com/oauth/authorize'
        params = {
            'response_type': 'code',
            'scope': 'read_write',
            'client_id': settings.STRIPE_CONNECT_CLIENT_ID,
            'redirect_uri': f'http://localhost:8000/account/oauth/callback'
        }
        url = f'{url}?{urllib.parse.urlencode(params)}'
        return redirect(url)



class StripeAuthorizeCallbackView(View):

    def get(self, request):
        code = request.GET.get('code')
        if code:
            data = {
                'client_secret': settings.STRIPE_SECRET_KEY,
                'grant_type': 'authorization_code',
                'client_id': settings.STRIPE_CONNECT_CLIENT_ID,
                'code': code
            }
            url = 'https://connect.stripe.com/oauth/token'
            resp = requests.post(url, params=data)
            # add stripe info to the seller
            stripe_user_id = resp.json()['stripe_user_id']
            stripe_access_token = resp.json()['access_token']
            seller = Seller.objects.filter(user_id=self.request.user.id).first()
            seller.stripe_access_token = stripe_access_token
            seller.stripe_user_id = stripe_user_id
            seller.save()
        url = reverse('home')
        response = redirect(url)
        return response

#LoginRequiredMixin,
class AccountHomeView(LoginRequiredMixin, DetailView):
   
    template_name = 'accounts/home.html'
    def get_object(self):
        return self.request.user

class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, "Your email has been confirmed. Please login.")
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = """Your email has already been confirmed
                    Do you need to <a href="{link}">reset your password</a>?
                    """.format(link=reset_link)
                    messages.success(request, mark_safe(msg))
                    return redirect("login") 
        context = {'form': self.get_form(),'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        # create form to receive an email
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = """Activation link sent, please check your email."""
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user 
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, "key": self.key }
        return render(self.request, 'registration/activation-error.html', context)

class GuestRegisterView(NextUrlMixin,  RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


def guest_register_view(request):
    form = GuestForm(request.POST or None)
    context = {
        "form": form
    }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None
    if form.is_valid():
        email       = form.cleaned_data.get("email")
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session['guest_email_id'] = new_guest_email.id
        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            return redirect("/register/")
    return redirect("/register/")



class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'
    


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Change Your Account Details'
        return context

    def get_success_url(self):
        return reverse("account:home")



# def login_page(request):
#     form = LoginForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     next_ = request.GET.get('next')
#     next_post = request.POST.get('next')
#     redirect_path = next_ or next_post or None
#     if form.is_valid():
#         username  = form.cleaned_data.get("username")
#         password  = form.cleaned_data.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             try:
#                 del request.session['guest_email_id']
#             except:
#                 pass
#             if is_safe_url(redirect_path, request.get_host()):
#                 return redirect(redirect_path)
#             else:
#                 return redirect("/")
#         else:
#             # Return an 'invalid login' error message.
#             print("Error")
#     return render(request, "accounts/login.html", context)

# User = get_user_model()
# def register_page(request):
#     form = RegisterForm(request.POST or None)
#     context = {
#         "form": form
#     }
#     if form.is_valid():
#         form.save()
#     return render(request, "accounts/register.html", context)

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}


{% block content %}
<div class='col-12 col-md-6 mx-auto'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" /><span class='help-text'>Cannot change email</span><br/>
  <button type='submit' class='btn btn-default my-3'>Save</button>
  <a href='{% url "password_change" %}'>Change Password</a>
</form>
</div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
<div class='col-12'>
<h1>Account</h1>
<hr/>
</div>
<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Support</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "about" %}'>About</a>
                <a class='list-group-item' href='{% url "contact" %}'>Contact</a>
            </div>
      </div>
    </div>
</div>



<div class='col-12 col-md-3 my-3' id='billing'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Billing</h4>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "orders:list" %}'>Orders</a>
                <a class='list-group-item' href='{% url "billing-payment-method" %}'>Payment Methods</a>
                <a class='list-group-item' href='{% url "addresses" %}'>Addresses</a>
                
                
            </div>
      </div>
    </div>
</div>


<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Account Details</h4> 
            <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-update" %}'>Update Details</a>
                <a class='list-group-item' href='{% url "password_change" %}'>Change Password</a>
                <a class='list-group-item' href='{% url "library" %}'>Library</a>
                
            </div>

      </div>
    </div>
</div>





<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">History</h4> 
              <div class='list-group'>
                <a class='list-group-item' href='{% url "account:user-product-history" %}'>Products</a>
            </div>
      </div>
    </div>
</div>

{% if user.is_authenticated and user.is_seller %}

<div class='col-12 col-md-3 my-3'>
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">bussnisse</h4>
        <div class='list-group'>
                <a class='list-group-item' href='{% url "stores:list" %}'>view other stores</a>
            </div>
              <div class='list-group'>
                <a class='list-group-item' href='{% url "stores:add_store" %}'>add your store now</a>
            </div>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "products:add_product" %}'>add product to your store</a>
            </div>
      </div>
    </div>
</div>
{% endif %}

</div>
<h1 class="title is-size-1">Django Stripe Connect</h1>
<hr><br>
{% if user.is_authenticated %}
  <p class="is-size-6">Welcome, {{ user.email }}!</p>
  <br>
  {% if user.is_seller and not user.seller.stripe_user_id %}
<a href="{% url 'account:authorize' %}" class="button is-info">Connect your Stripe Account</a>
{% endif %}
  <a href="{% url 'products:list' %}" class="button is-primary">Purchase A product</a>
{% else %}
  <p class="is-size-6">Please <a href="{% url '/login/' %}">log in</a>.</p>
{% endif %}


{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
    <form method='POST'> {% csrf_token %}
      {{ form.as_p }}
      <button type='submit' class='btn btn-default'>Submit</button>
    </form>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form method='POST'> {% csrf_token %}
    	
      {{ form.as_p }}
      <button type='submit' class='btn btn-default'>Submit</button>
    </form>

{% endblock %}